### PR TITLE
Create Greetings

### PR DESCRIPTION
**Pull request by yuehlin1**
I don't know how to send you messages so I sent a pull request. You can cancelled it if you want after reading the file " Create Greetings " thank you

### CODE REVIEW

**Comment by coraharmonica** [comment]
Hi sqohapoe!  The "big picture" problem I'm tackling with Blissymbols right now is creating more accurate/complete translations.  I've also coded a website which includes a Blissymbols translator, but I need a server to host it on.  I also encourage you to contact me if you see anything in my code worth commenting on!  I sent you an email with more information if you or any others are interested in getting involved.

**Comment by heatherleaf** [comment]
Dear @sqohapoe and @coraharmonica - thank you for your interest!

I have created an issue (#3) where you can write your ideas, CVs, links to other repos, etc. It would be most helpful if you could resubmit your thoughts as comments to that issue (#3) instead of this pull request!

**Comment by heatherleaf** [comment]
I'm closing this pull request, and direct everyone to issue #3 instead.

**Comment by yuehlin1** [comment]
Hi cora,

Sorry for not being able to reply you promptly in recent days. I don't
remember if we have already discussed the "big picture problem". Anyway,
I'll try to keep in contact with you.
By the way, I received another developer's mail about one writing keyboard
and one typing method non-semantically-based.
When it comes to the server, it seems that the team I participated before
working on a website of franco-taiwanese prepa system introduction has a
server. However since it's been some time that I didn't participate in the
project I am not in track of the current situation so I must ask.

Sincerely, yueh LIN (sqohapoe)

**Pull request closed without merging**
